#감정 매핑 파일

EMOTION_TO_FEATURE_44 = {
    "불평": {"valence": 0.3, "energy": 0.4, "danceability": 0.4},
    "환영": {"valence": 0.8, "energy": 0.6, "danceability": 0.6},
    "감동": {"valence": 0.7, "energy": 0.5, "danceability": 0.5},
    "지긋지긋": {"valence": 0.2, "energy": 0.3, "danceability": 0.3},
    "고마움": {"valence": 0.75, "energy": 0.5, "danceability": 0.5},
    "슬픔": {"valence": 0.2, "energy": 0.2, "danceability": 0.3},
    "화남": {"valence": 0.3, "energy": 0.8, "danceability": 0.5},
    "존경": {"valence": 0.65, "energy": 0.4, "danceability": 0.4},
    "기대감": {"valence": 0.7, "energy": 0.6, "danceability": 0.5},
    "우쭐댐": {"valence": 0.75, "energy": 0.7, "danceability": 0.6},
    "안타까움": {"valence": 0.3, "energy": 0.3, "danceability": 0.4},
    "비장함": {"valence": 0.4, "energy": 0.6, "danceability": 0.3},
    "의심": {"valence": 0.4, "energy": 0.4, "danceability": 0.3},
    "뿌듯함": {"valence": 0.8, "energy": 0.5, "danceability": 0.5},
    "편안": {"valence": 0.6, "energy": 0.3, "danceability": 0.4},
    "신기함": {"valence": 0.65, "energy": 0.5, "danceability": 0.5},
    "아껴주는": {"valence": 0.7, "energy": 0.4, "danceability": 0.4},
    "부끄러움": {"valence": 0.3, "energy": 0.3, "danceability": 0.3},
    "공포": {"valence": 0.1, "energy": 0.7, "danceability": 0.3},
    "절망": {"valence": 0.1, "energy": 0.2, "danceability": 0.2},
    "한심함": {"valence": 0.2, "energy": 0.3, "danceability": 0.3},
    "역겨움": {"valence": 0.1, "energy": 0.4, "danceability": 0.2},
    "짜증": {"valence": 0.3, "energy": 0.7, "danceability": 0.4},
    "어이없음": {"valence": 0.4, "energy": 0.4, "danceability": 0.3},
    "없음": {"valence": 0.5, "energy": 0.5, "danceability": 0.5},
    "패배": {"valence": 0.2, "energy": 0.3, "danceability": 0.3},
    "귀찮음": {"valence": 0.3, "energy": 0.3, "danceability": 0.3},
    "힘듦": {"valence": 0.2, "energy": 0.4, "danceability": 0.3},
    "즐거움": {"valence": 0.9, "energy": 0.7, "danceability": 0.8},
    "깨달음": {"valence": 0.7, "energy": 0.5, "danceability": 0.5},
    "죄책감": {"valence": 0.2, "energy": 0.3, "danceability": 0.3},
    "증오": {"valence": 0.1, "energy": 0.8, "danceability": 0.3},
    "흐뭇함": {"valence": 0.85, "energy": 0.6, "danceability": 0.6},
    "당황": {"valence": 0.4, "energy": 0.5, "danceability": 0.4},
    "경악": {"valence": 0.2, "energy": 0.8, "danceability": 0.4},
    "부담": {"valence": 0.3, "energy": 0.4, "danceability": 0.3},
    "서러움": {"valence": 0.2, "energy": 0.3, "danceability": 0.3},
    "재미없음": {"valence": 0.3, "energy": 0.2, "danceability": 0.2},
    "불쌍함": {"valence": 0.3, "energy": 0.3, "danceability": 0.3},
    "놀람": {"valence": 0.5, "energy": 0.6, "danceability": 0.5},
    "행복": {"valence": 0.95, "energy": 0.8, "danceability": 0.8},
    "불안": {"valence": 0.4, "energy": 0.6, "danceability": 0.4},
    "기쁨": {"valence": 0.9, "energy": 0.7, "danceability": 0.7},
    "안심": {"valence": 0.8, "energy": 0.4, "danceability": 0.5},
}

def get_target_features(emotion):
    # 매핑되지 않은 감정이면 중간값(평범) 반환
    return EMOTION_TO_FEATURE_44.get(emotion, {"valence": 0.5, "energy": 0.5})